technologiestiftung/erfrischungskarte-frontend

- public/data/curated_list_poi.geojson
This is the geojson that includes all the curated points of interest. The properties are showing the name, the category, the conditions (windig, kühl usw.), the district and the Bezirksregion.
> ERF-61: add geojson with curated lists of poi's

- src/components/HourSelector/index.tsx
- src/components/SplashScreen/index.tsx
- src/lib/hooks/useHasMobileSize/index.ts
- test/components/HourSelector/__snapshots__/HourSelector.stories.storyshot
- test/components/SplashScreen/__snapshots__/SplashScreen.stories.storyshot
in this PR im improving the mobile expirience
> fix: adjust mobile sizing

- src/modules/RefreshmentMap/content.ts
- src/modules/RefreshmentMap/index.tsx
This is WIP because we don't have valid tilesets for every hour yet. But we can merge if needed for testing purposes.
> ERF-55-map shadow tilesets

- pages/_app.tsx
- src/components/Map/Map.test.tsx
- src/components/Map/index.tsx
- src/components/MapExtrusionLayer/MapExtrusionLayer.test.tsx
- src/components/MapFilledPolygonLayer/MapFilledPolygonLayer.test.tsx
- src/components/MapPoiTooltip/MapPoiTooltip.css
- src/components/MapPoiTooltip/MapPoiTooltip.stories.tsx
- src/components/MapPoiTooltip/MapPoiTooltip.test.tsx
- src/components/MapPoiTooltip/index.tsx
- src/components/MapPointLayer/MapPointLayer.test.tsx
- src/components/MapRasterLayer/MapRasterLayer.test.tsx
- src/modules/RefreshmentMap/content.ts
- src/modules/RefreshmentMap/index.tsx
- test/components/MapPoiTooltip/__snapshots__/MapPoiTooltip.stories.storyshot
This PR adds the tooltip for the POIs.
> feat(ERF-58): POI tooltip

- src/style/global.css
This mini PR adds antialiasing to the font.
> style: make font smoother with antialiasing

- src/components/DisclaimerLinks/DisclaimerLinks.stories.tsx
- src/components/DisclaimerLinks/DisclaimerLinks.test.tsx
- src/components/DisclaimerLinks/index.tsx
- src/modules/RefreshmentMap/index.tsx
- test/components/DisclaimerLinks/__snapshots__/DisclaimerLinks.stories.storyshot
In this PR I am adding two links leading to Impressum and Datenschutz info
> ERF-63 disclaimer links

- src/components/HourSelector/HourSelector.stories.tsx
- src/components/HourSelector/HourSelector.test.tsx
- src/components/HourSelector/index.tsx
- src/lib/utils/queryUtil/index.ts
- src/lib/utils/queryUtil/queryUtil.test.ts
- src/modules/RefreshmentMap/index.tsx
- test/components/HourSelector/__snapshots__/HourSelector.stories.storyshot
This PR adds the functionality of filtering the map via URL query parameters:
> Feat:(ERF-60): Url query filters

- .github/CODEOWNERS
- README.md
This PR adds a simple README with basic infos about the repo
> feat(README): Update README with minimal infos

- pages/filters.tsx
- src/components/DisclaimerLinks/index.tsx
- src/components/Sidebar/index.tsx
- src/modules/RefreshmentMap/content.tsx
- src/modules/RefreshmentMap/index.tsx
- test/components/DisclaimerLinks/__snapshots__/DisclaimerLinks.stories.storyshot
- test/components/Sidebar/__snapshots__/Sidebar.stories.storyshot
- test/pages/stories/__snapshots__/search.stories.storyshot
This PR
- updates some text and formatting (@Lisa-Stubert can you take a look at a89add8?)
- updates and improves some styling
> refactor: various content and styles

- pages/about.tsx
- src/modules/RefreshmentMap/content.tsx
- test/pages/stories/__snapshots__/search.stories.storyshot
I added and rewrite some text in the about section, to be more precise about data sources and processing.
Also changed the wording from "windig" in the list with the POI's.
> ERF - 62 add texts

- pages/about.tsx
- src/modules/RefreshmentMap/content.tsx
This page adds a contact paragraph to the about section.
> feat(About): Add contact paragraph

- src/components/MapExtrusionLayer/index.tsx
- src/components/MapFilledPolygonLayer/index.tsx
- src/components/MapPointLayer/index.tsx
- src/components/MapRasterLayer/index.tsx
- src/modules/RefreshmentMap/index.tsx
> fix(Map): Add beforeId param to Map layer to enforce layer order

- pages/_app.tsx
- src/components/CookieBanner/CookieBanner.stories.tsx
- src/components/CookieBanner/CookieBanner.test.tsx
- src/components/CookieBanner/index.tsx
- test/components/CookieBanner/__snapshots__/CookieBanner.stories.storyshot
This PR adds a cookie banner component with basic accept/deny functionality
> feat(CookieBanner): Add CookieBanner

- package.json
This PR updates the `name` field in the `package.json` and removes the author of the Create Next App template.
> chore: update package.json info

- src/components/HourSelector/HourSelector.module.css
- src/components/HourSelector/HourSelector.test.tsx
- src/components/HourSelector/index.tsx
- src/lib/hooks/useCurrentTime/index.ts
- src/lib/hooks/useCurrentTime/useCurrentTime.test.tsx
- src/lib/utils/queryUtil/index.ts
- src/lib/utils/queryUtil/queryUtil.test.ts
- src/modules/RefreshmentMap/content.tsx
- src/style/colors.js
- test/components/HourSelector/__snapshots__/HourSelector.stories.storyshot
This PR shows the Moon/Star night indicator instead of the 21 o'clock option in the HourSelector component.
> feat(HourSelector): Show night indicator instead of hour 21

- src/components/MapExtrusionLayer/index.tsx
- src/modules/RefreshmentMap/content.tsx
- src/modules/RefreshmentMap/index.tsx
- Show shade layer by default
- Disallow zoom levels where no data is visible
> feat(ERF-108): adjust map zoom levels

- src/components/MapPointLayer/index.tsx
- src/modules/RefreshmentMap/index.tsx
The idea is to make POIs easier tappable on mobile.
> fix(ERF-107): increase POI radius for high zoom levels

- next-env.d.ts
- package-lock.json
- package.json
- pages/_app.tsx
- src/lib/hooks/useMatomo/index.tsx
This PR is an attempt to use our own matomo script with the `disableCookies` script on. I need to merge this branch in order to test it. So feel free to still comment on it and I will reopen it if needed!
> fix(matomo): Use own matomo script

- .vscode/settings.json
- src/components/SplashScreen/index.tsx
- test/components/SplashScreen/__snapshots__/SplashScreen.stories.storyshot
This PR applies Tori's text proposal for the splash screen based on Nico's Feedback
> chore(ERF-121): Change Text on Splash Screen based on Feedback

- .github/workflows/build.yml
> ci: change deprecated output command
